// Header
export const SET_CITY_LIST = "SET_CITY_LIST";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_IS_CITY_MODAL_OPEN = "SET_IS_CITY_MODAL_OPEN";
export const SET_IS_ACCEPTANCE_MODAL = "SET_IS_ACCEPTANCE_MODAL";

// Partners Page - Category
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST"; 
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY"; 
export const SET_SPASIBO_TYPE = "SET_SPASIBO_TYPE"; 
export const SET_FULL_CATEGORY_LIST = "SET_FULL_CATEGORY_LIST"; 
export const SET_SHORT_CATEGORY_LIST = "SET_SHORT_CATEGORY_LIST"; 
export const SET_PARTNERS_LIST = "SET_PARTNERS_LIST"; 
// Partners Page - Offers
export const SET_OFFERS_LIST = "SET_OFFERS_LIST"; 

// SingleOfferPage
export const SET_SINGLE_OFFER_PAGE = "SET_SINGLE_OFFER_PAGE"; 


