// Header
export const SET_CITY_LIST = "SET_CITY_LIST";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_IS_CITY_MODAL_OPEN = "SET_IS_CITY_MODAL_OPEN";
export const SET_IS_ACCEPTANCE_MODAL = "SET_IS_ACCEPTANCE_MODAL";