// Header
export const SET_CITY_LIST = "SET_CITY_LIST";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_IS_CITY_MODAL_OPEN = "SET_IS_CITY_MODAL_OPEN";
export const SET_IS_ACCEPTANCE_MODAL = "SET_IS_ACCEPTANCE_MODAL";

// Partners Page
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST"; 
export const SET_FULL_CATEGORY_LIST = "SET_FULL_CATEGORY_LIST"; 
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY"; 
export const SET_SHORT_CATEGORY_LIST = "SET_SHORT_CATEGORY_LIST"; 